### ISSUE TITLE
Problems with later releases of Ansible

### ISSUE THREAD

**Issue by ogenstad** [jedelman8/ansible-webdocs#1]
There seems to have be some issues with this module using later releases of Ansible. I'm able to create documentation using Ansible 1.8.4, but not with Ansible 1.9.1.

I'm able to create a task looking like this with Ansible 1.8.4
- name: print
  debug: msg="{{ item['module'] }}"
  with_items: modules.results

In 1.9.1 I can only do this:
- name: print
  debug: msg="{{ modules }}"

Basically the "register: modules" returns a different structure in different versions of Ansible.

I haven't done any more troubleshooting but wanted to let you know.

**Comment by jedelman8** [comment]
Can you show me the errors?

**Comment by ogenstad** [comment]
I think I found the issue.

In ansible_docstring:
doc, plainexamples = module_docs.get_docstring(path+mod)

Looking at the get_docstring function in Ansible 1.8.4 (https://github.com/ansible/ansible/blob/release1.8.4/lib/ansible/utils/module_docs.py) the function returns two objects:
return doc, plainexamples

However in Ansible 1.9.1 (https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs.py) the function returns three objects:
return doc, plainexamples, returndocs

This causes the try statement in ansible_docstring to fail and the module names are just appended to the 'errors' list.

So a quick solutions would be to just add another object:
doc, plainexamples, returndocs = module_docs.get_docstring(path+mod)

But that would instead break support for earlier releases. An ugly solution could be to just use two try statements. Or perhaps change it and say that the module requires 1.9 or later?

I can send you a pull request if you want to, but I won't have time to do it for some time.

**Comment by jedelman8** [comment]
Cool, appreciate it.  No, it's okay.  I'll dive in and hopefully come up with a fix that works in 1.8 and 1.9.

Thanks Patrick!

**Comment by ogenstad** [comment]
No problems, thank you for creating the module!

**Comment by jedelman8** [comment]
Fixed.
